[versions]
vaadin = "23.4.1"

[libraries]
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
# https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/
junit = "org.junit.jupiter:junit-jupiter-engine:5.11.0"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.13"
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:10.7"
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v23:1.4.5"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
